using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompany("合肥东青")] 
[assembly: AssemblyCopyright("Copyright ©  2014")]
[assembly: AssemblyTrademark("东青")]
// 程序集的版本信息由下面四个值组成:
//
//      主版本
//      数据库变更 
//      服务端变更
//      客户端变更
//
// 可以指定所有这些值，也可以使用“内部版本号”和“修订号”的默认值，
// 方法是按如下所示使用“*”:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("3.10.31.62")]
[assembly: AssemblyFileVersion("3.10.31.62")] 
 


